from __future__ import annotations
EXPANDED_GROUP_BOARDS = [
[{"label":"Inner planets","words":["MERCURY","VENUS","EARTH","MARS"]},{"label":"Outer planets","words":["JUPITER","SATURN","URANUS","NEPTUNE"]},{"label":"Space vehicles","words":["ROCKET","ROVER","PROBE","SHUTTLE"]},{"label":"Sky objects","words":["COMET","METEOR","ASTEROID","GALAXY"]}],
[{"label":"Ocean mammals","words":["WHALE","DOLPHIN","SEAL","MANATEE"]},{"label":"Seafood shellfish","words":["CRAB","LOBSTER","SHRIMP","CLAM"]},{"label":"Ocean zones","words":["REEF","SHORE","TRENCH","ABYSS"]},{"label":"Sailing terms","words":["MAST","SAIL","KEEL","RUDDER"]}],
[{"label":"Birds of prey","words":["EAGLE","HAWK","FALCON","OWL"]},{"label":"Water birds","words":["DUCK","GOOSE","HERON","SWAN"]},{"label":"Songbirds","words":["ROBIN","FINCH","THRUSH","WREN"]},{"label":"Bird anatomy","words":["BEAK","WING","TALON","FEATHER"]}],
[{"label":"Big cats","words":["LION","TIGER","JAGUAR","LEOPARD"]},{"label":"Bears","words":["POLAR","PANDA","GRIZZLY","BLACK"]},{"label":"Hoofed mammals","words":["DEER","MOOSE","ELK","BISON"]},{"label":"Small mammals","words":["OTTER","RABBIT","BADGER","BEAVER"]}],
[{"label":"Flying insects","words":["BEE","MOTH","FLY","WASP"]},{"label":"Crawling insects","words":["ANT","BEETLE","ROACH","TERMITE"]},{"label":"Butterfly stages","words":["EGG","LARVA","PUPA","ADULT"]},{"label":"Bug defenses","words":["STING","BITE","SHELL","CAMOUFLAGE"]}],
[{"label":"Tree parts","words":["ROOT","TRUNK","BRANCH","BARK"]},{"label":"Flower parts","words":["PETAL","STEM","PISTIL","SEPAL"]},{"label":"Garden herbs","words":["BASIL","MINT","THYME","SAGE"]},{"label":"Houseplants","words":["FERN","IVY","PALM","CACTUS"]}],
[{"label":"Citrus fruit","words":["LEMON","LIME","ORANGE","GRAPEFRUIT"]},{"label":"Stone fruit","words":["PEACH","PLUM","CHERRY","APRICOT"]},{"label":"Tropical fruit","words":["MANGO","PAPAYA","GUAVA","PINEAPPLE"]},{"label":"Berries","words":["STRAWBERRY","BLUEBERRY","RASPBERRY","BLACKBERRY"]}],
[{"label":"Root vegetables","words":["CARROT","BEET","TURNIP","RADISH"]},{"label":"Leafy greens","words":["KALE","SPINACH","CHARD","LETTUCE"]},{"label":"Squashes","words":["PUMPKIN","ZUCCHINI","ACORN","BUTTERNUT"]},{"label":"Alliums","words":["ONION","GARLIC","LEEK","SHALLOT"]}],
[{"label":"Cookware","words":["SKILLET","SAUCEPAN","WOK","KETTLE"]},{"label":"Utensils","words":["FORK","SPOON","WHISK","SPATULA"]},{"label":"Baking tools","words":["MIXER","SIFTER","ROLLING","SCALE"]},{"label":"Kitchen appliances","words":["OVEN","TOASTER","BLENDER","MICROWAVE"]}],
[{"label":"Living room","words":["SOFA","OTTOMAN","RECLINER","BOOKCASE"]},{"label":"Bedroom","words":["BED","DRESSER","WARDROBE","NIGHTSTAND"]},{"label":"Bathroom","words":["TOWEL","SOAP","SHAMPOO","TOOTHBRUSH"]},{"label":"Laundry","words":["HAMPER","DETERGENT","DRYER","IRON"]}],
[{"label":"Hand tools","words":["HAMMER","PLIERS","WRENCH","SCREWDRIVER"]},{"label":"Power tools","words":["DRILL","SANDER","JIGSAW","GRINDER"]},{"label":"Fasteners","words":["NAIL","SCREW","BOLT","RIVET"]},{"label":"Measuring tools","words":["RULER","LEVEL","CALIPER","TAPE"]}],
[{"label":"Classroom supplies","words":["PENCIL","ERASER","RULER","CRAYON"]},{"label":"School subjects","words":["MATH","HISTORY","SCIENCE","ENGLISH"]},{"label":"School places","words":["LIBRARY","GYM","CAFETERIA","OFFICE"]},{"label":"School people","words":["TEACHER","STUDENT","COACH","PRINCIPAL"]}],
[{"label":"Desk supplies","words":["STAPLER","PAPER","PEN","FOLDER"]},{"label":"Meetings","words":["AGENDA","MINUTES","CHAIR","NOTES"]},{"label":"Office tech","words":["PRINTER","MONITOR","LAPTOP","SCANNER"]},{"label":"Work roles","words":["MANAGER","ANALYST","CLERK","DIRECTOR"]}],
[{"label":"String instruments","words":["GUITAR","VIOLIN","CELLO","HARP"]},{"label":"Brass instruments","words":["TRUMPET","TROMBONE","TUBA","HORN"]},{"label":"Percussion","words":["DRUM","CYMBAL","TAMBOURINE","XYLOPHONE"]},{"label":"Music notation","words":["NOTE","REST","CLEF","STAFF"]}],
[{"label":"Movie genres","words":["COMEDY","DRAMA","HORROR","WESTERN"]},{"label":"Film crew","words":["DIRECTOR","EDITOR","GAFFER","PRODUCER"]},{"label":"At a cinema","words":["SCREEN","POPCORN","TRAILER","TICKET"]},{"label":"Film awards","words":["OSCAR","GLOBE","BAFTA","EMMY"]}],
[{"label":"Stage areas","words":["WING","APRON","ORCHESTRA","BACKSTAGE"]},{"label":"Theater jobs","words":["ACTOR","USHER","DIRECTOR","DESIGNER"]},{"label":"Stage items","words":["PROP","CURTAIN","SET","SPOTLIGHT"]},{"label":"Show types","words":["MUSICAL","DRAMA","COMEDY","OPERA"]}],
[{"label":"Book genres","words":["MYSTERY","ROMANCE","FANTASY","THRILLER"]},{"label":"Book parts","words":["COVER","SPINE","PAGE","CHAPTER"]},{"label":"Library terms","words":["STACKS","CATALOG","LOAN","SHELF"]},{"label":"Publishing roles","words":["AUTHOR","EDITOR","AGENT","PRINTER"]}],
[{"label":"Painting media","words":["OIL","ACRYLIC","WATERCOLOR","GOUACHE"]},{"label":"Drawing tools","words":["PENCIL","CHARCOAL","PASTEL","MARKER"]},{"label":"Art venues","words":["GALLERY","MUSEUM","STUDIO","SALON"]},{"label":"Design elements","words":["LINE","SHAPE","COLOR","TEXTURE"]}],
[{"label":"Camera settings","words":["ISO","SHUTTER","APERTURE","FOCUS"]},{"label":"Camera gear","words":["LENS","TRIPOD","FLASH","FILTER"]},{"label":"Photo subjects","words":["PORTRAIT","LANDSCAPE","SPORT","WILDLIFE"]},{"label":"Editing terms","words":["CROP","EXPOSURE","CONTRAST","SATURATION"]}],
[{"label":"Track events","words":["SPRINT","HURDLES","RELAY","MARATHON"]},{"label":"Field events","words":["DISCUS","JAVELIN","SHOT","VAULT"]},{"label":"Swimming strokes","words":["FREESTYLE","BACKSTROKE","BREASTSTROKE","BUTTERFLY"]},{"label":"Gymnastics apparatus","words":["RINGS","BARS","BEAM","VAULT"]}]
]
